services:
  mysql:
    image: mysql:latest
    restart: always
    env_file: .env
    ports:
      - "3310:3306"
    volumes:
      - ./.srv/database:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    ports:
      - "8000:80"
    volumes:
      - ./.srv/wordpress:/var/www/html
      - ./custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./.htaccess:/var/www/html/
      - ./.htpasswd:/var/www/html/
    depends_on:
      - mysql
    links:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    environment:
      MYSQL_USERNAME: $MYSQL_USER
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      PMA_HOST: mysql
    ports:
      - "8181:80"
    depends_on:
      - mysql
    links:
      - mysql